            - name: cairo-format-action
  # You may pin to the exact commit or the version.
  # uses: milancermak/cairo-format-action@2f62eb06aba71999c42406a20d52fcfdd071538e
  uses: milancermak/cairo-format-action@v1
  with:
    # The directory containing .cairo files to be checked for formatting, relative to the repo root.
    target: # optional, default is contracts
    # cairo-lang package version to be installed. Action uses the latest published one by default.
    cairo-version: # optional
    # Additional arguments passed to cairo-format
    cairo-format-args: # optional
          
